### PR TITLE
add Toxiproxy.running? method to check if proxy is running

### PR DESCRIPTION
**Pull request by dwradcliffe**
ref: https://github.com/rubygems/rubygems.org/pull/995

r: @Sirupsen @xthexder

### CODE REVIEW

**Comment by xthexder** [comment]
Seems resonable :+1: 
Adding a test might be good.

**Comment by dwradcliffe** [comment]
Not sure how to test since toxiproxy is running throughout the test...

**Comment by xthexder** [comment]
Maybe just asserting that it will at least return true would be fine.
Testing toxiproxy not running would require something like, you know... toxiproxy in front. :confused:

**Comment by dwradcliffe** [comment]
Added a simple test and the flaky test seems to pass now too.

**Comment by Sirupsen** [comment]
@dwradcliffe 0.1.3 with this patch has been pushed to Rubygems

**Comment by dwradcliffe** [comment]
Thanks!

**Pull request merged**
