### PR TITLE
Update toxiproxy version to 2.1.0

### PR DESCRIPTION
**Pull request by douglas**

### CODE REVIEW

**Comment by sirupsen** [comment]
We have https://github.com/Shopify/toxiproxy/issues/159 which is problematic in 2.0.0 still. I'd like to wait.

**Comment by douglas** [comment]
No problem, @sirupsen =)

**Comment by sirupsen** [comment]
If you're up for it @Douglas, you could try tackling that bug in Toxiproxy and then we can merge this 🙃

**Comment by douglas** [comment]
Hello @sirupsen!

Well, I have been working hard to have the Python wrapper totally compatible with the Ruby one but I guess it is usable by now =)

I don't know much of Go, but I read some of the code and I could understand some of it, perhaps it can be a great way to learn more.

Also, what do you and @xthexder recommends to debug this kind of problems? I still have lots of things to learn about network programming and I'm not sure how to "look behind the scenes" to see what is going on.

I was planning to reproduce the issue and try to use strace or gdb to see what is happening but I don't know how effective this approach is when it envolves networking.

Thanks!

**Comment by jpittis** [comment]
I think we can go ahead and update. We decided that the bug is also present in version `2.0.0` and removed our recommendation to not upgrade with https://github.com/Shopify/toxiproxy/pull/165.

**Comment by sirupsen** [comment]
👍

**Pull request merged**
